CREATE TABLE barcodes
(
    id          INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    barcode     VARCHAR(255)              DEFAULT NULL,
    insert_time TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
)
ENGINE = InnoDB
DEFAULT CHARSET = utf8;
